version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - ./data:/data # Ruta local ./data mapeada al directorio /data del contenedor
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data: